site_name: DoaNet
site_url: https://mdsreq-fga-unb.github.io/REQ-2026.1-T01-DoaNet/

nav:
  - Home: index.md
  - Guias Tecnicos:
      - Backend (Poetry + Django + Postgres): poetry-django-setup.md
      - Frontend (Flutter): flutter-setup.md
  
  - Visão De Produto e Projeto:
      - 1. Cenário Atual: visao_produto/1-cenario.md
      - 2. Solução Proposta: visao_produto/2-solucao.md
      - 3. Intervenção Social: visao_produto/3-IntervencaoSocial.md
      - 4. Estratégias de ES: visao_produto/4-estrategia.md
      - 5. Engenharia de Requisitos de ES: visao_produto/5-EngenhariadeRequisitos.md
      - 6. Planejamento: visao_produto/6-planejamento.md
      - 7. Interação com Cliente: visao_produto/7-interacao.md
      - 8. Requisitos: visao_produto/8-requisitos.md
      - 9. DOR e DOD: visao_produto/9-DorEDod.md
      - 10. Backlog: visao_produto/10-backlog_do_produto.md
      - 11. Lições Aprendidas: visao_produto/11-licoes.md
  - Atas de Reunião:
      - Modelo: atas/modelo.md
      - Reunião 1: atas/ata1_27_04_2026.md
      - Reunião 2: atas/ata2_04_05_2026.md
      - Reunião 3: atas/ata3_11_05_2026.md
  - Exemplos de Documentação: example.md
  - Como Manter o Git Pages: mkdocs-tutorial.md



theme:
  name: material
  palette:
    - scheme: default
      primary: black
      accent: blue
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.tabbed
  - admonition