site_name: DoaNet
site_url: https://mdsreq-fga-unb.github.io/REQ-2026.1-T01-DoaNet/

nav:
  - Home: index.md
  - Visão De Produto e Projeto:
      - 1. Cenário Atual: visao_produto/1-cenario.md
      - 2. Solução Proposta: visao_produto/2-solucao.md
      - 3. Estratégias de ES: visao_produto/3-estrategia.md
      - 4. Engenharia de Requisitos de ES: visao_produto/4-EngenhariadeRequisitos.md
      - 5. Planejamento: visao_produto/5-planejamento.md
      - 6. Interação com Cliente: visao_produto/6-interacao.md
      - 10. Lições Aprendidas: visao_produto/10-licoes.md




theme:
  name: material
  palette:
    - scheme: default
      primary: black
      accent: blue
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.tabbed
  - admonition